id: IBB34BBF9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:02:28+00:00'
last_modified: '2022-06-08T07:37:19.157636+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD4
  title: མན་ངག་ལྷན་ཐབས་དང་ལྡེ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8ED6:
      image_group_id: I1PD403
      title: ''
      total_pages: 763
      order: 1
      base_file: 8ED6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
